project:
  type: website
  output-dir: docs
  
website:
  title: "temp_website"
<<<<<<< HEAD
  
navbar:
  left:
    - href: index.qmd
      text: Home
    - href: fyp.qmd
      text: Project
    - href: data-visualization.qmd
      text: Data Visualization
=======
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
>>>>>>> 973ca5522affe038dce6a7f5f51669cca569e229

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

